export const LoginTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_RESPONSE: "LOGIN_RESPONSE",
  LOGIN_RESPONSE_CLEAR: "LOGIN_RESPONSE_CLEAR",
  ERROR_RESPONSE: "ERROR_RESPONSE",
  ERROR_RESPONSE_CLEAR: "ERROR_RESPONSE_CLEAR",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_RESPONSE: "REGISTER_RESPONSE",
  REGISTER_RESPONSE_CLEAR: "REGISTER_RESPONSE_CLEAR",

  GET_CURR_USER_REQUEST: "GET_CURR_USER_REQUEST",
  GET_CURR_USER_RESPONSE: "GET_CURR_USER_RESPONSE",
  GET_CURR_USER_RESPONSE_CLEAR: "GET_CURR_USER_RESPONSE_CLEAR",
};
