export const TaskTypes = {
  GET_ALL_TASK_REQUEST: "GET_ALL_TASK_REQUEST",
  GET_ALL_TASK_RESPONSE: "GET_ALL_TASK_RESPONSE",
  GET_ALL_TASK_RESPONSE_CLEAR: "GET_ALL_TASK_RESPONSE_CLEAR",

  GET_TASK_BY_ID_REQUEST: "GET_TASK_BY_ID_REQUEST",
  GET_TASK_BY_ID_RESPONSE: "GET_TASK_BY_ID_RESPONSE",
  GET_TASK_BY_ID_RESPONSE_CLEAR: "GET_TASK_BY_ID_RESPONSE_CLEAR",

  POST_TASK_REQUEST: "POST_TASK_REQUEST",
  POST_TASK_RESPONSE: "POST_TASK_RESPONSE",
  POST_TASK_RESPONSE_CLEAR: "POST_TASK_RESPONSE_CLEAR",

  PUT_TASK_REQUEST: "PUT_TASK_REQUEST",
  PUT_TASK_RESPONSE: "PUT_TASK_RESPONSE",
  PUT_TASK_RESPONSE_CLEAR: "PUT_TASK_RESPONSE_CLEAR",

  DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
  DELETE_TASK_RESPONSE: "DELETE_TASK_RESPONSE",
  DELETE_TASK_RESPONSE_CLEAR: "DELETE_TASK_RESPONSE_CLEAR",
};
